### ISSUE TITLE
Demo, Readme and Implementation for RadioButton

### ISSUE THREAD

**Issue by pleku** [vaadin/vaadin-radio-button-flow#1]
Java API for https://github.com/vaadin/vaadin-radio-button with Demo and similar README as with other Flow components.

This is excluding the `RadioButtonGroup` component `vaadin-radio-button-group` for now!

### Acceptance criteria:
- There is a `RadioButton` component that I'm able to test
- There is an example which has some bolded text inside some radio button and an icon inside another (this would require a test dependency to `vaadin-icons-flow`, which is still pending vaadin/flow#2796)
- There is a readme file

**Comment by denis-anisimov** [comment]
The repository for the component: https://github.com/vaadin/vaadin-radio-button-flow

**Comment by denis-anisimov** [comment]
Should this ticket be closed?

**Comment by pleku** [comment]
Yes
