### ISSUE TITLE
Working HasValue API for RadioButtonGroup

### ISSUE THREAD

**Issue by pleku** [vaadin/vaadin-radio-button-flow#12]
Until https://github.com/vaadin/vaadin-radio-button/issues/18 is done and released, we cannot have API like `setErrorMessage` and `setRequired` working.

### Acceptance Criteria
- There is a demo that shows the usage of required and error message for that.

**Comment by pleku** [comment]
Looks like this won't be done for the `1.0` version of the component which is included in V10.

**Comment by ZheSun88** [comment]
The blocking ticket has been closed and Code has been generated with the latest version.
