### ISSUE TITLE
Adding components in between RadioButtonGroup items

### ISSUE THREAD

**Issue by pleku** [vaadin/vaadin-radio-button-flow#5]
```When showing a radio button group to users, I want to add headers/separators between the options, so that the user can better distinct between different set of options```

API proposal that allows two ways of adding items and mixing components with those:
(note any `setItems` call or change of `DataProvider` should remove all previously added items and components)
```java
RadioButtonGroup<T> extends SingleSelect<T> {

...

/**
 * Adds the components as after the currently last item.
 */
public void addComponents(Component... components) { ... } 

/**
 * Adds the components after the given item.
 * The item must have be added to group via setItems/dataProvider/addItems
 */
public void addComponents(T afterItem, Component... components) { ... }

public void removeComponent(Component component) { ... }
}
```

### Acceptance Criteria
- there is an example for `RadioButtonGroup` where there are headers and separators for different sections used
- there is an example for `RadioButtonGroup` where the contents are changing based on selecting something else, which means that the content is updated dynamically by removing and adding options
  - this should make it clear that `setItems(..)` or changing dataProvider will clear everything

**Comment by Legioth** [comment]
This approach implies that a `RadioButton` added using `addComponents` could also be selected and should affect the return value of `RadioButtonGroup::getValue`. This in turn implies that the item should be stored inside the `RadioButtonGorup` and be configured separately.

**Comment by pleku** [comment]
>This approach implies that a RadioButton added using addComponents could also be selected and should affect the return value of RadioButtonGroup::getValue. This in turn implies that the item should be stored inside the RadioButtonGorup and be configured separately.
Not an issue since `RadioButton` is not exposed, people can ofcourse make their own but we don't have to support such foolishness.
