### ISSUE TITLE
RadioButtonGroup component

### ISSUE THREAD

**Issue by denis-anisimov** [vaadin/vaadin-radio-button-flow#7]
See #4 
It's a part if the epic.

The very first steps to do : 
- Generate the radio button group component ( the result should be inside `flow-generated-components` module).
- Copy generated code to the `https://github.com/vaadin/vaadin-radio-button-flow`  repository.
- Extend the generated component and implement the `SingleSelect` interface.
- It should support setting data provider or items via the `setItems` method. Implement `HasItems`.
- by default, for each item the content for the vaadin-radio-button element is created as text with call of Object.toString() on the item

EDIT: [see comment below](https://github.com/vaadin/vaadin-radio-button-flow/issues/7#issuecomment-344882144)

**Comment by pleku** [comment]
Note that #12 has been added and thus those methods should just throw a `NotSupportedOperationException` for now.
