### ISSUE TITLE
"Radio button group with icon generator" Java demo has a lot of whitespace

### ISSUE THREAD

**Issue by mickoyuh** [vaadin/vaadin-radio-button-flow#70]
From Gitlab. By Artur. 
--
https://vaadin.com/elements/vaadin-radio-button/java-examples

Why is there a huge white space before each icon? I would not want that

![image](https://user-images.githubusercontent.com/26737661/43195178-f408575c-900c-11e8-80d6-968d7cbe0b8e.png)

**Comment by web-padawan** [comment]
The demos have been updated so there is no more such demo.
