### ISSUE TITLE
Confusing "Add component to group" Java radio button demo

### ISSUE THREAD

**Issue by mickoyuh** [vaadin/vaadin-radio-button-flow#71]
From Gitlab, by Artur. 
--
https://vaadin.com/elements/vaadin-radio-button/java-examples

It's unclear what the demo is trying to show

**Comment by web-padawan** [comment]
I think the demo should be removed as there are other demos with components in radio group.

**Comment by web-padawan** [comment]
The demos have been updated and there is no more such demo.
