### ISSUE TITLE
The demo "Move component in group on selection" causes a server-side exception

### ISSUE THREAD

**Issue by gilberto-torrezan** [vaadin/vaadin-radio-button-flow#81]
The demo titled "Move component in group on selection" in https://vaadin.com/components/vaadin-radio-button/java-examples is causing server-side exceptions, that cause the page to refresh, leading to a bad UX and log pollution on the webserver.

Steps to reproduce:

1. Click on the first radio button of the demo (foo);
2. Click on the second radio button of the demo (foo-bar).

The server-side error is:

```
IllegalArgumentException: Could not locate the item after which to insert components.
at com.vaadin.flow.component.radiobutton.demo.RadioButtonGroupView.lambda$dynamicComponents$2d6cb63e$1(RadioButtonGroupView.java:324)
```

**Comment by paulroemer** [comment]
Still valid!

**Comment by web-padawan** [comment]
Seems like this is no longer valid. At least the page refresh doesn't happen.
