### ISSUE TITLE
RadioButtonGroup should use DataRefreshEvent for item refresh

### ISSUE THREAD

**Issue by pleku** [vaadin/vaadin-radio-button-flow#82]
Currently any single item refresh will cause full DOM rebuild instead of just updating the required item.

The `DataProviderListener` in RBG should check for the type of the received event, and on the case of `DataRefreshEvent` it should just refresh that radio button instead of doing a full refresh.

**Comment by denis-anisimov** [comment]
Fixed by https://github.com/vaadin/vaadin-radio-button-flow/pull/84
